In [1]:
import numpy as np

In [3]:
LIST = [1,2,3,4]
LIST

[1, 2, 3, 4]

In [5]:
array = np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [6]:
LIST = [[1,2,3],[4,5,6],[7,8,9]]
LIST

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [19]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [15]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])